# Generated by Django 5.0.4 on 2024-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_chat_reciver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.URLField(
                default="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/340px-Default_pfp.svg.png"
            ),
        ),
    ]
